#!/usr/bin/env python3
"""Check official DH conference source pages for published changes.

The script intentionally avoids fully automatic fact changes. Conference pages
vary widely, and reviewed updates are better than brittle scraping. On a
scheduled run it records changed source hashes and writes a concise review
report; GitHub Actions opens a pull request when files change.
"""

from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import re
import textwrap
import urllib.error
import urllib.request
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
WATCH_FILE = ROOT / "_data" / "source_watch.yml"
REPORT_DIR = ROOT / "reports"


def fetch(url: str, timeout: int = 25) -> str:
    request = urllib.request.Request(
        url,
        headers={
            "User-Agent": "dh-conference-radar/0.1 (+https://github.com/)",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
        },
    )
    with urllib.request.urlopen(request, timeout=timeout) as response:
        charset = response.headers.get_content_charset() or "utf-8"
        return response.read().decode(charset, errors="replace")


def normalize_html(html: str) -> str:
    html = re.sub(r"<script\b[^>]*>.*?</script>", " ", html, flags=re.I | re.S)
    html = re.sub(r"<style\b[^>]*>.*?</style>", " ", html, flags=re.I | re.S)
    text = re.sub(r"<[^>]+>", " ", html)
    text = re.sub(r"\s+", " ", text)
    return text.strip()


def digest(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def snippets(text: str) -> list[str]:
    patterns = [
        r".{0,80}(?:conference|congress|annual|dates?|registration|call for papers|cfp).{0,120}",
        r".{0,80}(?:2026|2027|2028|2029).{0,120}",
    ]
    found: list[str] = []
    for pattern in patterns:
        for match in re.finditer(pattern, text, flags=re.I):
            snippet = match.group(0).strip()
            if snippet not in found:
                found.append(snippet)
            if len(found) >= 5:
                return found
    return found


def parse_scalar(value: str) -> str:
    value = value.strip()
    if len(value) >= 2 and value[0] == value[-1] == '"':
        return value[1:-1]
    return value


def quote_scalar(value: object) -> str:
    text = "" if value is None else str(value)
    escaped = text.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def load_watch() -> dict:
    sources: list[dict] = []
    current: dict | None = None

    for raw_line in WATCH_FILE.read_text(encoding="utf-8").splitlines():
        line = raw_line.rstrip()
        stripped = line.strip()
        if not stripped or stripped == "sources:":
            continue
        if stripped.startswith("- "):
            if current:
                sources.append(current)
            current = {}
            stripped = stripped[2:]
        if ":" in stripped and current is not None:
            key, value = stripped.split(":", 1)
            current[key.strip()] = parse_scalar(value)

    if current:
        sources.append(current)
    return {"sources": sources}


def save_watch(data: dict) -> None:
    lines = ["sources:"]
    for source in data.get("sources", []):
        lines.append(f"  - id: {quote_scalar(source.get('id', ''))}")
        for key in ("label", "url", "purpose", "selector_hint", "last_hash", "last_checked"):
            if key in source:
                lines.append(f"    {key}: {quote_scalar(source.get(key, ''))}")
        lines.append("")
    WATCH_FILE.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def write_report(changes: list[dict], failures: list[dict]) -> Path:
    REPORT_DIR.mkdir(exist_ok=True)
    today = dt.date.today().isoformat()
    report = REPORT_DIR / f"source-check-{today}.md"
    lines = [
        f"# Source check: {today}",
        "",
        "This report was generated by `scripts/update_conferences.py`.",
        "",
    ]

    if changes:
        lines.extend(["## Changed Sources", ""])
        for change in changes:
            lines.extend(
                [
                    f"### {change['label']}",
                    "",
                    f"- URL: {change['url']}",
                    f"- Previous hash: `{change['old_hash'] or 'none'}`",
                    f"- Current hash: `{change['new_hash']}`",
                    "",
                    "Review cues:",
                    "",
                ]
            )
            for snippet in change["snippets"]:
                wrapped = textwrap.fill(snippet, width=100)
                lines.append(f"- {wrapped}")
            lines.append("")
    else:
        lines.extend(["## Changed Sources", "", "No source changes detected.", ""])

    if failures:
        lines.extend(["## Fetch Failures", ""])
        for failure in failures:
            lines.extend([f"- {failure['label']}: {failure['error']} ({failure['url']})"])
        lines.append("")

    report.write_text("\n".join(lines), encoding="utf-8")
    return report


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--dry-run", action="store_true", help="Check sources without writing files.")
    parser.add_argument("--no-network", action="store_true", help="Validate configuration only.")
    args = parser.parse_args()

    data = load_watch()
    sources = data.get("sources", [])
    if not sources:
        raise SystemExit("No sources configured in _data/source_watch.yml")

    changes: list[dict] = []
    failures: list[dict] = []

    if args.no_network:
        print(f"Validated {len(sources)} source definitions.")
        return 0

    for source in sources:
        try:
            html = fetch(source["url"])
            text = normalize_html(html)
            new_hash = digest(text)
            old_hash = source.get("last_hash") or ""
            source["last_checked"] = dt.date.today().isoformat()
            if old_hash != new_hash:
                changes.append(
                    {
                        "label": source["label"],
                        "url": source["url"],
                        "old_hash": old_hash,
                        "new_hash": new_hash,
                        "snippets": snippets(text),
                    }
                )
                source["last_hash"] = new_hash
        except (urllib.error.URLError, TimeoutError, UnicodeError) as exc:
            failures.append({"label": source["label"], "url": source["url"], "error": str(exc)})

    if args.dry_run:
        print(f"{len(changes)} changed source(s), {len(failures)} failure(s).")
        return 1 if failures else 0

    if changes:
        save_watch(data)
    if changes or failures:
        report = write_report(changes, failures)
        print(f"Wrote {report.relative_to(ROOT)}")
    else:
        print("No source changes detected.")
    print(f"{len(changes)} changed source(s), {len(failures)} failure(s).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
